# Generated by Django 3.2.7 on 2021-11-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infofeed', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
